on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push to Docker hub wordpress:8.2
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.php8.2-fpm
        push: true
        tags: mikakoivisto/wordpress:php8.2-fpm
    - name: Build and push to Docker hub wordpress:7.4
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.php7.4-fpm
        push: true
        tags: mikakoivisto/wordpress:php7.4-fpm